openapi: 3.0.1
info:
  title: Swagger Observation Sealife
  description: Swagger Observation Sealife
  version: 1.0.0
servers:
  - url: http://localhost:8080/seaLife
paths:
  /observation-sheet:
    post:
      summary: Create a observation sheet
      operationId: newObservationSheet
      tags:
        - observation-sheet
      requestBody:
        content:
          'application/json':
            schema:
              $ref: "#/components/schemas/ObservationSheetDto"
        required: true
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/ObservationSheetDto"
        '400':
          description: BAD REQUEST
  /species:
    get:
      operationId: findSpecies
      tags:
        - species
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                type: string
components:
  schemas:
    ObservationSheetDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        islandId:
          type: string
        distanceFromIsland:
          type: integer
          format: int32
        observationDate:
          type: string
          format: date-time
        observationQuality:
          type: string
          enum:
            - SUSPICION
            - PROBABLE
            - VERIFIE
        animalName:
          type: string
        specie:
          type: string
          enum:
            - MAMMIFERE
            - POISSON
        size:
          type: integer
          format: int32
        isBank:
          type: boolean
        apneaTime:
          type: integer
          format: int32




  
