server:
  servlet:
    context-path: /seaLife
springdoc:
  show-actuator: true
  swagger-ui:
    urls:
      - url: "/api.yaml"
        name: local
    urls-primary-name: local
    disable-swagger-default-url: true

spring:
  application:
    name: SeaLife Observations
  datasource:
    url: 'jdbc:h2:mem:sealifedb'
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type: trace
        stat: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
client:
  ilotsNC:
    url: https://www.province-sud.nc/pandoreweb
